#!/usr/bin/env python3
"""Generate per-domain cleanup prompts for cpp. Auto-generated by pipeline/run_pipeline.py."""

import importlib.util
import os
from pathlib import Path

_spec = importlib.util.spec_from_file_location(
    "_tmpl", Path(__file__).parent.parent / "template.py"
)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
TEMPLATE = _mod.TEMPLATE

DOMAINS = [
    (0, "collections", "C++ — Collections", 13),
    (1, "type_system", "C++ — Type System", 11),
    (2, "control_flow", "C++ — Control Flow", 9),
    (3, "io", "C++ — I/O", 8),
    (4, "concurrency", "C++ — Concurrency", 9),
    (5, "functional", "C++ — Functional", 9),
    (6, "memory", "C++ — Memory", 8),
    (7, "templates", "C++ — Templates", 8),
    (8, "pointers", "C++ — Pointers", 8),
    (9, "raii", "C++ — RAII", 11),
]

BASE = "/home/jimbob/Dev/AWS_Dev"
DATA_DIR = "data/cpp_domains"


def main():
    out_dir = os.path.dirname(os.path.abspath(__file__))
    for idx, slug, display_name, term_count in DOMAINS:
        content = TEMPLATE.format(
            idx=idx,
            slug=slug,
            display_name=display_name,
            term_count=term_count,
            base=BASE,
            data_dir=DATA_DIR,
        )
        out_path = os.path.join(out_dir, f"domain_{idx:02d}_{slug}.md")
        with open(out_path, "w") as f:
            f.write(content)
        print(f"  Written: domain_{idx:02d}_{slug}.md  ({term_count} terms)")
    print(f"\nGenerated {len(DOMAINS)} prompt files in {out_dir}/")


if __name__ == "__main__":
    main()
