#!/usr/bin/env python3
"""Cleanup pipeline agent.

Handles slug derivation, split/merge script generation, and the per-domain
ReAct tool-calling loop against Sparky (Qwen3.5-35B on local vLLM).
"""

import json
import re
import subprocess
import sys
from pathlib import Path

import requests

# ── Sparky ────────────────────────────────────────────────────────────────────
SPARKY_BASE = "http://192.168.1.104:8004/v1"
SPARKY_MODEL = "qwen35-35b-a3b"
PROJECT_ROOT = Path(__file__).parent.parent

# ── Tool definitions for Qwen3 function calling ───────────────────────────────
TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "read_file",
            "description": (
                "Read the full text content of a file and return it as a string. "
                "Use this wherever the task says 'Use the Read tool'."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "Absolute path to the file"}
                },
                "required": ["path"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "write_file",
            "description": (
                "Write content to a file, creating or overwriting it. "
                "Use this wherever the task says 'Use the Write tool'."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "path": {"type": "string", "description": "Absolute path to the file"},
                    "content": {"type": "string", "description": "Complete content to write"},
                },
                "required": ["path", "content"],
            },
        },
    },
]

SYSTEM_PROMPT = """\
You are a definition cleanup agent with two file tools:
  read_file(path)          — reads a file (replaces "Use the Read tool" in instructions)
  write_file(path,content) — writes a file (replaces "Use the Write tool" in instructions)

Follow the task instructions exactly. Use read_file to inspect the source file,
then use write_file once to write the completed output file.
"""


# ── Slug / stem derivation ────────────────────────────────────────────────────
_ABBREVS = {
    "management": "mgmt",
    "preparation": "prep",
    "architectural": "arch",
    "infrastructure": "infra",
    "introduction": "intro",
    "operations": "ops",
}


def derive_slug(domain_name: str) -> str:
    """'Java — String Operations' → 'string_ops'"""
    label = domain_name.split(" — ", 1)[-1]
    slug = label.lower()
    slug = slug.replace("/", "")  # "I/O" → "io"
    slug = re.sub(r"[\s\-]+", "_", slug)  # spaces/hyphens → _
    slug = re.sub(r"[^\w]", "", slug)  # strip remaining non-word chars
    slug = re.sub(r"_+", "_", slug).strip("_")

    for long, short in _ABBREVS.items():
        slug = slug.replace(long, short)

    for suffix in ("_foundations", "_overview"):
        if slug.endswith(suffix):
            slug = slug[: -len(suffix)]

    # "x_and_y": replace connector, then truncate if still long
    slug = re.sub(r"_and_", "_", slug)
    if len(slug) > 15:
        slug = slug.split("_")[0]

    return slug


def derive_stem(upload_path: Path) -> tuple[str, str, Path]:
    """Returns (stem, stem_nodash, fix_output_path).
    'java_upload.json'        → ('java', 'java', .../java_upload-fix.json)
    'java_upload-fix.json'    → ('java', 'java', .../java_upload-fix.json)
    'ai_ml_upload-fix.json'   → ('ai_ml', 'aiml', .../ai_ml_upload-fix.json)
    The fix output path is always the -fix.json variant, never the raw source.
    """
    stem = re.sub(r"_upload.*$", "", upload_path.name)
    stem_nodash = stem.replace("_", "")
    fix_path = upload_path.parent / f"{stem}_upload-fix.json"
    return stem, stem_nodash, fix_path


# ── Script generation ─────────────────────────────────────────────────────────
def _write_split_script(
    domains: list[tuple[int, str, str, int]],
    stem_nodash: str,
    upload_filename: str,
    output_dir: Path,
) -> Path:
    path = output_dir / f"split_{stem_nodash}_domains.py"
    if path.exists():
        return path

    slugs_block = "\n".join(f'    "{slug}",' for _, slug, _, _ in domains)
    n = len(domains)
    path.write_text(f'''\
#!/usr/bin/env python3
"""
Split {upload_filename} into {n} per-sub-domain files.
Generated by pipeline/run_pipeline.py — do not edit manually.
"""
import json, os

SLUGS = [
{slugs_block}
]

def main():
    data_dir = os.path.dirname(os.path.abspath(__file__))
    src = os.path.join(data_dir, "..", "{upload_filename}")
    with open(src) as f:
        data = json.load(f)
    domains = data["domains"]
    assert len(domains) == len(SLUGS), f"Expected {{len(SLUGS)}} domains, got {{len(domains)}}"
    for i, (domain, slug) in enumerate(zip(domains, SLUGS)):
        out_path = os.path.join(data_dir, f"domain_{{i:02d}}_{{slug}}.json")
        payload = {{
            "domain_index": i,
            "domain_name": domain["data"]["name"],
            "term_count": len(domain["terms"]),
            "terms": domain["terms"],
        }}
        with open(out_path, "w") as f:
            json.dump(payload, f, indent=2)
        print(f"  {{i:02d}}. {{domain[\'data\'][\'name\']:40s}} → {{os.path.basename(out_path)}}  ({{len(domain[\'terms\'])}} terms)")
    print(f"\\nCreated {{len(domains)}} domain files in {{data_dir}}/")

if __name__ == "__main__":
    main()
''')
    return path


def _write_merge_script(
    domains: list[tuple[int, str, str, int]],
    stem_nodash: str,
    src_filename: str,
    fix_filename: str,
    display_prefix: str,
    output_dir: Path,
) -> Path:
    path = output_dir / f"merge_{stem_nodash}_domains.py"
    if path.exists():
        return path

    n = len(domains)
    domains_block = "\n".join(f'    ({idx}, "{slug}", "{name}"),' for idx, slug, name, _ in domains)
    path.write_text(f'''\
#!/usr/bin/env python3
"""
Checkpoint reporter and merger for {display_prefix} domain definition cleanup.
Generated by pipeline/run_pipeline.py — do not edit manually.

Usage:
  python3 merge_{stem_nodash}_domains.py           # report status
  python3 merge_{stem_nodash}_domains.py --merge   # merge all {n} completed domains
"""
import json, os, sys

DOMAINS = [
{domains_block}
]

def main():
    do_merge = "--merge" in sys.argv
    data_dir = os.path.dirname(os.path.abspath(__file__))
    src_path = os.path.join(data_dir, "..", "{src_filename}")
    out_path = os.path.join(data_dir, "..", "{fix_filename}")

    with open(src_path) as f:
        source = json.load(f)

    print("=== {display_prefix} Domain Cleanup Checkpoint ===\\n")
    completed, errors, pending = [], [], []

    for idx, slug, display_name in DOMAINS:
        fix_path = os.path.join(data_dir, f"domain_{{idx:02d}}_{{slug}}_fix.json")
        if os.path.exists(fix_path):
            try:
                with open(fix_path) as f:
                    fix_data = json.load(f)
                terms = fix_data.get("terms", [])
                expected = len(source["domains"][idx]["terms"])
                if len(terms) != expected:
                    raise ValueError(f"expected {{expected}} terms, got {{len(terms)}}")
                print(f"  ✓  {{idx:02d}}. {{display_name:40s}} ({{len(terms)}} terms)")
                completed.append((idx, slug, fix_path, fix_data))
            except (json.JSONDecodeError, ValueError, KeyError) as e:
                print(f"  ✗  {{idx:02d}}. {{display_name:40s}} (ERROR: {{e}})")
                errors.append((idx, slug, str(e)))
        else:
            print(f"  …  {{idx:02d}}. {{display_name:40s}} (pending)")
            pending.append((idx, slug))

    total = len(DOMAINS)
    print(f"\\n{{len(completed)}}/{{total}} done  |  {{len(errors)}} errors  |  {{len(pending)}} pending")

    if pending:
        next_idx, next_slug = pending[0]
        print(f"\\nNext: domain_{{next_idx:02d}}_{{next_slug}}.md")
    if errors:
        print("\\nFix errors before merging:")
        for idx, slug, msg in errors:
            print(f"  domain_{{idx:02d}}_{{slug}}_fix.json — {{msg}}")

    if not do_merge:
        if len(completed) == total and not errors:
            print(f"\\nAll {{total}} domains complete. Run with --merge to update {fix_filename}")
        return

    if errors or pending:
        print("\\nCannot merge: not all domains are complete and error-free.")
        sys.exit(1)

    print(f"\\nMerging all {{total}} domains into {fix_filename} ...")
    merged = {{"domains": []}}
    for idx, slug, fix_path, fix_data in completed:
        original = source["domains"][idx]
        merged["domains"].append({{
            "node_type": original["node_type"],
            "data":      original["data"],
            "terms":     fix_data["terms"],
        }})

    with open(out_path, "w") as f:
        json.dump(merged, f, indent=2)

    total_terms = sum(len(d["terms"]) for d in merged["domains"])
    print(f"Written: {{out_path}}  ({{total_terms}} terms across {{len(merged[\'domains\'])}} domains)")

if __name__ == "__main__":
    main()
''')
    return path


def _write_generate_prompts_script(
    domains: list[tuple[int, str, str, int]],
    stem: str,
    data_dir_rel: str,
    prompt_dir: Path,
) -> Path:
    """Generate pipeline/02_cleanup/{stem}/generate_prompts.py if not present."""
    prompt_dir.mkdir(parents=True, exist_ok=True)
    script_path = prompt_dir / "generate_prompts.py"
    if script_path.exists():
        return script_path

    domains_block = "\n".join(
        f'    ({idx}, "{slug}", "{name}", {count}),' for idx, slug, name, count in domains
    )
    script_path.write_text(f'''\
#!/usr/bin/env python3
"""Generate per-domain cleanup prompts for {stem}. Auto-generated by pipeline/run_pipeline.py."""
import importlib.util, os
from pathlib import Path

_spec = importlib.util.spec_from_file_location("_tmpl", Path(__file__).parent.parent / "template.py")
_mod  = importlib.util.module_from_spec(_spec); _spec.loader.exec_module(_mod)
TEMPLATE = _mod.TEMPLATE

DOMAINS = [
{domains_block}
]

BASE     = "/home/jimbob/Dev/AWS_Dev"
DATA_DIR = "{data_dir_rel}"


def main():
    out_dir = os.path.dirname(os.path.abspath(__file__))
    for idx, slug, display_name, term_count in DOMAINS:
        content = TEMPLATE.format(
            idx=idx, slug=slug, display_name=display_name,
            term_count=term_count, base=BASE, data_dir=DATA_DIR,
        )
        out_path = os.path.join(out_dir, f"domain_{{idx:02d}}_{{slug}}.md")
        with open(out_path, "w") as f:
            f.write(content)
        print(f"  Written: domain_{{idx:02d}}_{{slug}}.md  ({{term_count}} terms)")
    print(f"\\nGenerated {{len(DOMAINS)}} prompt files in {{out_dir}}/")


if __name__ == "__main__":
    main()
''')
    return script_path


# ── Tool dispatcher ───────────────────────────────────────────────────────────
def _dispatch(name: str, args: dict) -> str:
    if name == "read_file":
        p = Path(args["path"])
        if not p.exists():
            return f"ERROR: file not found: {args['path']}"
        return p.read_text()
    if name == "write_file":
        p = Path(args["path"])
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(args["content"])
        return "OK"
    return f"ERROR: unknown tool '{name}'"


def _sparky(messages: list, tools: list) -> dict:
    """Stream from Sparky and accumulate into a single response dict.
    Streaming avoids read timeouts on long reasoning chains.
    max_tokens=8192 is sufficient for cleanup (short_reference generation needs 32768).
    """
    payload = {
        "model": SPARKY_MODEL,
        "messages": messages,
        "tools": tools,
        "tool_choice": "auto",
        "max_tokens": 24576,
        "temperature": 0.2,
        "stream": True,
    }

    content_parts: list[str] = []
    reasoning_parts: list[str] = []
    tool_calls_acc: dict[int, dict] = {}
    finish_reason: str | None = None

    with requests.post(
        f"{SPARKY_BASE}/chat/completions",
        json=payload,
        stream=True,
        timeout=(30, None),  # 30s connect, unlimited read
    ) as resp:
        resp.raise_for_status()
        for raw in resp.iter_lines():
            if not raw or not raw.startswith(b"data: "):
                continue
            payload_bytes = raw[6:]
            if payload_bytes == b"[DONE]":
                break
            chunk = json.loads(payload_bytes)
            choice = chunk["choices"][0]
            finish_reason = choice.get("finish_reason") or finish_reason
            delta = choice.get("delta", {})

            if delta.get("content"):
                content_parts.append(delta["content"])
            if delta.get("reasoning"):
                reasoning_parts.append(delta["reasoning"])

            for tc in delta.get("tool_calls") or []:
                i = tc["index"]
                if i not in tool_calls_acc:
                    tool_calls_acc[i] = {
                        "id": "",
                        "type": "function",
                        "function": {"name": "", "arguments": ""},
                    }
                if tc.get("id"):
                    tool_calls_acc[i]["id"] = tc["id"]
                fn = tc.get("function", {})
                if fn.get("name"):
                    tool_calls_acc[i]["function"]["name"] += fn["name"]
                if fn.get("arguments"):
                    tool_calls_acc[i]["function"]["arguments"] += fn["arguments"]

    return {
        "choices": [
            {
                "finish_reason": finish_reason,
                "message": {
                    "role": "assistant",
                    "content": "".join(content_parts) or None,
                    "reasoning": "".join(reasoning_parts) or None,
                    "tool_calls": list(tool_calls_acc.values()),
                },
            }
        ]
    }


# ── Per-domain cleanup agent ──────────────────────────────────────────────────
def run_cleanup_agent(
    prompt_path: Path,
    fix_path: Path,
    term_count: int,
    log,
    max_turns: int = 25,
) -> bool:
    """Run a single-domain cleanup agent against Sparky.
    Reads the prompt from prompt_path (.md file).
    log: open file object — turn-level details written here, not to stdout.
    Returns True if _fix.json was successfully written and validated.
    Skips without calling Sparky if fix_path already exists.
    """
    if fix_path.exists():
        log.write(f"[{fix_path.name}] skipped — already done\n")
        print("(already done)")
        return True

    prompt = prompt_path.read_text()

    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": prompt},
    ]

    wrote_fix = False
    for turn in range(max_turns):
        data = _sparky(messages, TOOLS)
        choice = data["choices"][0]
        msg = choice["message"]
        messages.append(msg)

        finish = choice.get("finish_reason", "stop")
        tool_calls = msg.get("tool_calls") or []

        if finish == "tool_calls" or tool_calls:
            tool_results = []
            for tc in tool_calls:
                fn_name = tc["function"]["name"]
                try:
                    args = json.loads(tc["function"]["arguments"])
                except json.JSONDecodeError:
                    log.write(f"  turn {turn + 1}: FAIL — tool call arguments truncated\n")
                    log.flush()
                    print("\n     FAIL: see log for details")
                    return False
                path_arg = str(args.get("path", ""))
                log.write(f"  turn {turn + 1}: {fn_name}({path_arg})\n")
                log.flush()
                result = _dispatch(fn_name, args)
                tool_results.append(
                    {
                        "role": "tool",
                        "tool_call_id": tc["id"],
                        "content": result,
                    }
                )
                if fn_name == "write_file":
                    wrote_fix = True
            messages.extend(tool_results)
            if wrote_fix:
                break
        else:
            # finish_reason == "stop"
            content_len = len(msg.get("content") or "")
            log.write(
                f"  turn {turn + 1}: stop — content_len={content_len}, wrote_fix={wrote_fix}\n"
            )
            log.flush()
            if wrote_fix:
                break
            # Model output text instead of calling write_file — redirect it
            messages.append(
                {
                    "role": "user",
                    "content": (
                        "You must save your output by calling write_file — do not output JSON as text. "
                        f"Call write_file now with path='{fix_path}' "
                        "and the complete rewritten JSON as the content argument."
                    ),
                }
            )

    if not wrote_fix:
        msg = f"FAIL: {max_turns} turns completed without write_file call"
        log.write(f"  {msg}\n")
        log.flush()
        print(f"\n     {msg}")
        return False
    if not fix_path.exists():
        msg = f"FAIL: write_file called but {fix_path.name} not found on disk"
        log.write(f"  {msg}\n")
        log.flush()
        print(f"\n     {msg}")
        return False

    # Validate: parseable JSON with correct term count
    try:
        with open(fix_path) as f:
            data = json.load(f)
        actual = len(data.get("terms", []))
        if actual != term_count:
            msg = f"FAIL: expected {term_count} terms, got {actual}"
            log.write(f"  {msg}\n")
            log.flush()
            print(f"\n     {msg}")
            return False
    except json.JSONDecodeError as e:
        msg = f"FAIL: output is not valid JSON: {e}"
        log.write(f"  {msg}\n")
        log.flush()
        print(f"\n     {msg}")
        return False

    return True


# ── Main pipeline ─────────────────────────────────────────────────────────────
def run_pipeline(upload_path: Path) -> None:
    upload_path = upload_path.resolve()
    if not upload_path.exists():
        sys.exit(f"Error: {upload_path} not found")

    stem, stem_nodash, fix_output_path = derive_stem(upload_path)
    output_dir = upload_path.parent / f"{stem}_domains"
    output_dir.mkdir(exist_ok=True)

    with open(upload_path) as f:
        data = json.load(f)

    raw_domains = data["domains"]
    display_prefix = raw_domains[0]["data"]["name"].split(" — ")[0] if raw_domains else stem.upper()

    domains = [
        (i, derive_slug(d["data"]["name"]), d["data"]["name"], len(d["terms"]))
        for i, d in enumerate(raw_domains)
    ]

    data_dir_rel = f"data/{stem}_domains"
    prompt_dir = Path(__file__).parent / "02_cleanup" / stem

    # ── Step 1: Generate split, merge, and generate_prompts scripts ───────────
    print(f"\n[1/4] Preparing {output_dir.name}/")
    for idx, slug, name, count in domains:
        print(f"       {idx:02d}. {name:40s} → slug: {slug}  ({count} terms)")

    split_script = _write_split_script(domains, stem_nodash, upload_path.name, output_dir)
    merge_script = _write_merge_script(
        domains,
        stem_nodash,
        src_filename=upload_path.name,
        fix_filename=fix_output_path.name,
        display_prefix=display_prefix,
        output_dir=output_dir,
    )
    gen_py = _write_generate_prompts_script(domains, stem, data_dir_rel, prompt_dir)
    print(f"  scripts: {split_script.name}, {merge_script.name}, {gen_py.name}")

    # ── Step 2: Split into per-domain JSON files ──────────────────────────────
    first = output_dir / f"domain_00_{domains[0][1]}.json"
    if not first.exists():
        print(f"\n[2/4] Splitting {upload_path.name} ...")
        subprocess.run([sys.executable, str(split_script)], check=True)
    else:
        print("\n[2/4] Per-domain files already present, skipping split.")

    # ── Step 3: Generate per-domain cleanup prompt .md files ─────────────────
    first_md = prompt_dir / f"domain_00_{domains[0][1]}.md"
    if not first_md.exists():
        print(f"\n[3/4] Generating cleanup prompts in {prompt_dir.relative_to(PROJECT_ROOT)}/")
        subprocess.run([sys.executable, str(gen_py)], check=True)
    else:
        print("\n[3/4] Cleanup prompts already present, skipping generate.")

    # ── Step 4: Per-domain cleanup via Sparky ────────────────────────────────
    log_dir = PROJECT_ROOT / "pipeline" / "logs"
    log_dir.mkdir(exist_ok=True)
    from datetime import datetime

    log_path = log_dir / f"{stem}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"

    print(f"\n[4/4] Cleanup — {len(domains)} domains via Sparky")
    print(f"      log: {log_path.relative_to(PROJECT_ROOT)}")
    failed = []

    with open(log_path, "w") as log:
        log.write(f"Pipeline run: {upload_path.name}\n")
        log.write(f"Domains: {len(domains)}\n\n")

        for idx, slug, display_name, term_count in domains:
            prompt_path = prompt_dir / f"domain_{idx:02d}_{slug}.md"
            fix_path = output_dir / f"domain_{idx:02d}_{slug}_fix.json"
            print(f"  {idx:02d}. {display_name} ({term_count} terms) ... ", end="", flush=True)
            log.write(f"[{idx:02d}] {display_name} ({term_count} terms)\n")
            log.flush()
            ok = run_cleanup_agent(prompt_path, fix_path, term_count, log)
            status = "ok" if ok else "FAILED"
            log.write(f"  result: {status}\n\n")
            log.flush()
            print("✓" if ok else "✗ FAILED")
            if not ok:
                failed.append((idx, slug))

    if failed:
        names = ", ".join(f"domain_{i:02d}_{s}" for i, s in failed)
        print(f"\n  {len(failed)} domain(s) failed: {names}")
        print("  Re-run to retry failed domains (completed ones will be skipped).")
        sys.exit(1)

    # ── Step 5: Merge ─────────────────────────────────────────────────────────
    print(f"\n[5/5] Merge → {fix_output_path.name}")
    subprocess.run([sys.executable, str(merge_script), "--merge"], check=True)
    print("\nPipeline complete.")
